# vim:sw=2:et:
sudo: false

language: generic

addons:
  apt:
    packages:
      - xsltproc
      - python3

otp_release:
  - "R16B03-1"
  - "17.5"
  - "18.3"
  - "19.0"
  - "19.1"
  - "19.2"

# The checkout made by Travis is a "detached HEAD" and branches
# information is missing. Our Erlang.mk's git_rmq fetch method relies on
# it, so we need to restore it.
#
# We simply fetch master and, if it exists, stable branches. A branch is
# created, pointing to the detached HEAD.
before_script:
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream stable:stable || :
    git fetch upstream master:master || :
  # Remove all kiex installations. This makes sure that the Erlang
  # Solutions one is picked: it's after the kiex installations in $PATH.
  - kiex list known
  - kiex install 1.5.1

script: make tests

cache:
  apt: true
